### ISSUE TITLE
Translation to kyrgyz

### ISSUE THREAD

**Issue by Entea** [Entea/coronavirus-kyrgyzcha#1]
Need to translate table headers and page title
```
                            {title: 'Country'},
                            {title: 'Confirmed total'},
                            {title: 'Confirmed growth'},
                            {title: 'Recovered total'},
                            {title: 'Recovered growth'},
                            {title: 'Deaths total'},
                            {title: 'Deaths growth'},
```

**Comment by jumasheff** [comment]
{title: 'Өлкө'},
                            {title: 'Ырасталгандар'},
                            {title: 'Ырасталгандар, өсүшү'},
                            {title: 'Айыккандар'},
                            {title: 'Айыккандар, өсүшү'},
                            {title: 'Өлгөндөр'},
                            {title: 'Өлгөндөр, өсүшү'},

**Comment by Entea** [comment]
"Ырасталган"- муну "Бака брат" тушунбойт ко
"Ооругандар" деп койсо деле болот

**Comment by jumasheff** [comment]
Адрестелди :)
